use crate::ast::{BinaryOp, Expr, Program, Stmt, UnaryOp};

pub struct CodeGen {
    output: String,
    indent_level: usize,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
        }
    }

    pub fn generate(mut self, program: &Program) -> String {
        self.emit_line("// Generated by Gage Native Compiler (AOT)");
        self.emit_line("#include <stdio.h>");
        self.emit_line("#include <stdlib.h>");
        self.emit_line("#include <stdbool.h>");
        self.emit_line("#include <math.h>");
        self.emit_line("");
        
        // Native SIMD Vector Structs
        self.emit_line("typedef struct { double x, y; } gage_vec2;");
        self.emit_line("typedef struct { double x, y, z; } gage_vec3;");
        self.emit_line("typedef struct { double x, y, z, w; } gage_vec4;");
        self.emit_line("");
        
        // Vector constructors
        self.emit_line("static inline gage_vec2 make_vec2(double x, double y) { return (gage_vec2){x, y}; }");
        self.emit_line("static inline gage_vec3 make_vec3(double x, double y, double z) { return (gage_vec3){x, y, z}; }");
        self.emit_line("static inline gage_vec4 make_vec4(double x, double y, double z, double w) { return (gage_vec4){x, y, z, w}; }");
        self.emit_line("");

        // Vector Arithmetic Helpers
        self.emit_line("static inline gage_vec3 vec3_add(gage_vec3 a, gage_vec3 b) { return (gage_vec3){a.x + b.x, a.y + b.y, a.z + b.z}; }");
        self.emit_line("static inline gage_vec3 vec3_sub(gage_vec3 a, gage_vec3 b) { return (gage_vec3){a.x - b.x, a.y - b.y, a.z - b.z}; }");
        self.emit_line("static inline gage_vec3 vec3_mul(gage_vec3 a, double s) { return (gage_vec3){a.x * s, a.y * s, a.z * s}; }");
        self.emit_line("");

        // Native Print Overloads
        self.emit_line("static inline void gage_println_str(const char* s) { printf(\"%s\\n\", s); }");
        self.emit_line("static inline void gage_println_int(long long n) { printf(\"%lld\\n\", n); }");
        self.emit_line("static inline void gage_println_float(double f) { printf(\"%f\\n\", f); }");
        self.emit_line("static inline void gage_println_vec3(gage_vec3 v) { printf(\"vec3(%f, %f, %f)\\n\", v.x, v.y, v.z); }");
        self.emit_line("");

        self.emit_line("int main(int argc, char** argv) {");
        self.indent_level += 1;

        for stmt in &program.statements {
            self.gen_stmt(stmt);
        }

        self.emit_line("return 0;");
        self.indent_level -= 1;
        self.emit_line("}");

        self.output
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { name, initializer, .. } => {
                let init_expr = self.gen_expr(initializer);
                self.emit_line(&format!("__auto_type {} = {};", name, init_expr));
            }
            Stmt::Assign { name, value } => {
                let val_expr = self.gen_expr(value);
                self.emit_line(&format!("{} = {};", name, val_expr));
            }
            Stmt::Expression(expr) => {
                let expr_str = self.gen_expr(expr);
                self.emit_line(&format!("{};", expr_str));
            }
            Stmt::Block(stmts) => {
                self.emit_line("{");
                self.indent_level += 1;
                for s in stmts {
                    self.gen_stmt(s);
                }
                self.indent_level -= 1;
                self.emit_line("}");
            }
            Stmt::If { condition, then_branch, else_branch } => {
                let cond = self.gen_expr(condition);
                self.emit_line(&format!("if ({}) {{", cond));
                self.indent_level += 1;
                self.gen_stmt(then_branch);
                self.indent_level -= 1;
                if let Some(eb) = else_branch {
                    self.emit_line("} else {");
                    self.indent_level += 1;
                    self.gen_stmt(eb);
                    self.indent_level -= 1;
                }
                self.emit_line("}");
            }
            Stmt::While { condition, body } => {
                let cond = self.gen_expr(condition);
                self.emit_line(&format!("while ({}) {{", cond));
                self.indent_level += 1;
                self.gen_stmt(body);
                self.indent_level -= 1;
                self.emit_line("}");
            }
            Stmt::Loop { body } => {
                self.emit_line("while (1) {");
                self.indent_level += 1;
                self.gen_stmt(body);
                self.indent_level -= 1;
                self.emit_line("}");
            }
            Stmt::Step { dt_ident, body } => {
                self.emit_line("{");
                self.indent_level += 1;
                self.emit_line(&format!("double {} = 0.016667;", dt_ident));
                self.gen_stmt(body);
                self.indent_level -= 1;
                self.emit_line("}");
            }
            Stmt::Break => self.emit_line("break;"),
            Stmt::Continue => self.emit_line("continue;"),
            Stmt::Return(maybe_expr) => {
                if let Some(e) = maybe_expr {
                    let r = self.gen_expr(e);
                    self.emit_line(&format!("return {};", r));
                } else {
                    self.emit_line("return 0;");
                }
            }
            Stmt::Function { body, .. } => {
                self.gen_stmt(body);
            }
        }
    }

    fn gen_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Int(n) => n.to_string(),
            Expr::Float(f) => format!("{:.6}", f),
            Expr::Str(s) => format!("\"{}\"", s),
            Expr::Bool(b) => if *b { "1".to_string() } else { "0".to_string() },
            Expr::Nil => "0".to_string(),
            Expr::Variable(name) => name.clone(),
            Expr::Binary { left, op, right } => {
                let l = self.gen_expr(left);
                let r = self.gen_expr(right);
                match op {
                    BinaryOp::Add => format!("({} + {})", l, r),
                    BinaryOp::Sub => format!("({} - {})", l, r),
                    BinaryOp::Mul => format!("({} * {})", l, r),
                    BinaryOp::Div => format!("({} / {})", l, r),
                    BinaryOp::Equal => format!("({} == {})", l, r),
                    BinaryOp::NotEqual => format!("({} != {})", l, r),
                    BinaryOp::Less => format!("({} < {})", l, r),
                    BinaryOp::LessEqual => format!("({} <= {})", l, r),
                    BinaryOp::Greater => format!("({} > {})", l, r),
                    BinaryOp::GreaterEqual => format!("({} >= {})", l, r),
                }
            }
            Expr::Unary { op, expr } => {
                let e = self.gen_expr(expr);
                match op {
                    UnaryOp::Negate => format!("(-{})", e),
                    UnaryOp::Not => format!("(!{})", e),
                }
            }
            Expr::Call { callee, args } => {
                let rendered_args: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
                if callee == "println" {
                    if let Some(arg) = args.first() {
                        match arg {
                            Expr::Str(_) => format!("gage_println_str({})", rendered_args.join(", ")),
                            Expr::Int(_) => format!("gage_println_int({})", rendered_args.join(", ")),
                            Expr::Float(_) => format!("gage_println_float({})", rendered_args.join(", ")),
                            Expr::Vec3(_, _, _) => format!("gage_println_vec3({})", rendered_args.join(", ")),
                            _ => format!("printf(\"%lld\\n\", (long long){})", rendered_args.join(", ")),
                        }
                    } else {
                        "printf(\"\\n\")".to_string()
                    }
                } else {
                    format!("{}({})", callee, rendered_args.join(", "))
                }
            }
            Expr::Vec2(x, y) => format!("make_vec2({}, {})", self.gen_expr(x), self.gen_expr(y)),
            Expr::Vec3(x, y, z) => format!("make_vec3({}, {}, {})", self.gen_expr(x), self.gen_expr(y), self.gen_expr(z)),
            Expr::Vec4(x, y, z, w) => format!("make_vec4({}, {}, {}, {})", self.gen_expr(x), self.gen_expr(y), self.gen_expr(z), self.gen_expr(w)),
        }
    }

    fn emit_line(&mut self, text: &str) {
        let indent = "    ".repeat(self.indent_level);
        self.output.push_str(&format!("{}{}\n", indent, text));
    }
}
